'use client'
import { CalendarDays, Clock, MapPin, Music, Gift, Heart, Images, MailCheck, Timer } from 'lucide-react'
import { formatEventDate } from '@/lib/projects'

export function SiteSectionRenderer({ section, project, theme }) {
  if (!section?.visible) return null
  const p = theme?.palette || { bg:'#F8F4EC', accent:'#C9A96E', text:'#101827', muted:'#8B8577' }
  const props = section.props || {}
  const names = [project?.host_a, project?.host_b].filter(Boolean).join(' & ') || 'Özel Günümüz'
  const shell = 'mx-auto w-full max-w-5xl px-5 py-16 sm:px-8 sm:py-24'
  const heading = 'font-serif text-3xl sm:text-5xl'
  const maps = 'https://www.google.com/maps/search/?api=1&query=' + encodeURIComponent([project?.venue,project?.address,project?.city].filter(Boolean).join(', '))

  if (section.type === 'hero') return <section className="relative flex min-h-[620px] items-center justify-center overflow-hidden text-center" style={{background:p.bg,color:p.text}}>{project?.hero_image && <img src={project.hero_image} alt="" className="absolute inset-0 h-full w-full object-cover" style={{opacity:Number(project.hero_image_opacity??30)/100}}/>}<div className="absolute inset-0" style={{background:p.bg+'cc'}}/><div className="relative z-10 px-6"><p className="text-[10px] uppercase tracking-[0.35em]" style={{color:p.accent}}>{props.eyebrow||'Davetlisiniz'}</p><h1 className="mt-5 font-serif text-5xl leading-tight sm:text-7xl">{props.title||names}</h1><div className="mx-auto my-6 h-px w-16" style={{background:p.accent}}/><p className="text-sm sm:text-base" style={{color:p.muted}}>{props.subtitle||formatEventDate(project?.date,project?.time)}</p>{(project?.venue||project?.city)&&<p className="mt-4 flex items-center justify-center gap-2 text-xs" style={{color:p.muted}}><MapPin className="h-3.5 w-3.5" style={{color:p.accent}}/>{[project?.venue,project?.city].filter(Boolean).join(' · ')}</p>}</div></section>
  if (section.type === 'story') return <section style={{background:p.bg,color:p.text}}><div className={shell+' text-center'}><p className="text-[10px] uppercase tracking-[0.35em]" style={{color:p.accent}}>{props.label}</p><h2 className={heading+' mt-4'}>{props.title}</h2><p className="mx-auto mt-7 max-w-2xl whitespace-pre-line font-serif text-lg leading-relaxed sm:text-2xl" style={{color:p.muted}}>{props.body||project?.story||'Hikâyenizi buraya ekleyin.'}</p></div></section>
  if (section.type === 'event') return <section style={{background:p.bg,color:p.text}}><div className={shell}><div className="text-center"><p className="text-[10px] uppercase tracking-[0.35em]" style={{color:p.accent}}>Etkinlik</p><h2 className={heading+' mt-4'}>{props.title}</h2></div><div className="mt-10 grid gap-px sm:grid-cols-3" style={{background:p.accent+'33'}}><Info icon={CalendarDays} label="Tarih" value={project?.date?new Date(project.date+'T12:00:00').toLocaleDateString('tr-TR',{day:'numeric',month:'long',year:'numeric'}):'—'} p={p}/><Info icon={Clock} label="Saat" value={project?.time||'—'} p={p}/><Info icon={MapPin} label="Mekân" value={project?.venue||'—'} p={p}/></div>{props.showFamilies&&(project?.bride_mother||project?.groom_mother)&&<p className="mt-8 text-center text-sm" style={{color:p.muted}}>Ailelerimiz de bu güzel günde sizlerle olacak.</p>}</div></section>
  if (section.type === 'location') return <section style={{background:p.bg,color:p.text}}><div className={shell+' text-center'}><MapPin className="mx-auto h-6 w-6" style={{color:p.accent}}/><h2 className={heading+' mt-4'}>{props.title}</h2><p className="mt-4 text-sm" style={{color:p.muted}}>{[project?.venue,project?.address,project?.city].filter(Boolean).join(', ')||'Konum bilgisi ekleyin.'}</p>{(project?.venue||project?.address)&&<a href={maps} target="_blank" rel="noreferrer" className="mt-6 inline-flex rounded-full px-5 py-3 text-[10px] uppercase tracking-[0.2em]" style={{background:p.accent,color:p.bg}}>Yol tarifi al</a>}</div></section>
  if (section.type === 'gallery') return <section style={{background:p.bg,color:p.text}}><div className={shell}><div className="text-center"><Images className="mx-auto h-6 w-6" style={{color:p.accent}}/><h2 className={heading+' mt-4'}>{props.title}</h2></div><div className="mt-10 grid min-h-48 grid-cols-2 gap-3 sm:grid-cols-3">{(props.images?.length?props.images:[project?.hero_image].filter(Boolean)).map((src,i)=><img key={i} src={src} alt="" className="h-56 w-full rounded-2xl object-cover"/>)}</div></div></section>
  if (section.type === 'countdown') return <section style={{background:p.bg,color:p.text}}><div className={shell+' text-center'}><Timer className="mx-auto h-6 w-6" style={{color:p.accent}}/><h2 className={heading+' mt-4'}>{props.title}</h2><div className="mx-auto mt-8 grid max-w-2xl grid-cols-4 gap-2">{['Gün','Saat','Dakika','Saniye'].map(x=><div key={x} className="border py-5" style={{borderColor:p.accent+'44'}}><b className="font-serif text-3xl">--</b><p className="mt-1 text-[9px] uppercase tracking-widest" style={{color:p.muted}}>{x}</p></div>)}</div></div></section>
  if (section.type === 'rsvp') return <section style={{background:p.bg,color:p.text}}><div className={shell+' text-center'}><MailCheck className="mx-auto h-6 w-6" style={{color:p.accent}}/><h2 className={heading+' mt-4'}>{props.title}</h2><p className="mx-auto mt-4 max-w-md text-sm" style={{color:p.muted}}>Davetliniz katılım durumunu bu alandan bildirebilir.</p><div className="mx-auto mt-8 max-w-md rounded-2xl border p-6 text-left" style={{borderColor:p.accent+'44'}}><div className="h-10 rounded-lg border" style={{borderColor:p.accent+'33'}}/><div className="mt-3 h-10 rounded-lg border" style={{borderColor:p.accent+'33'}}/><button className="mt-4 h-11 w-full rounded-full text-[10px] uppercase tracking-widest" style={{background:p.accent,color:p.bg}}>Katılımımı bildir</button></div></div></section>
  if (section.type === 'music') return <section style={{background:p.bg,color:p.text}}><div className={shell+' text-center'}><Music className="mx-auto h-6 w-6" style={{color:p.accent}}/><h2 className={heading+' mt-4'}>{props.title}</h2><p className="mt-4 text-sm" style={{color:p.muted}}>{project?.spotify_url?'Spotify çalma listeniz yayında.':'Spotify bağlantınızı ekleyin.'}</p></div></section>
  if (section.type === 'gift') return <section style={{background:p.bg,color:p.text}}><div className={shell+' text-center'}><Gift className="mx-auto h-6 w-6" style={{color:p.accent}}/><h2 className={heading+' mt-4'}>{props.title}</h2><p className="mx-auto mt-4 max-w-md text-sm" style={{color:p.muted}}>{project?.gift_message||'Hediye tercihlerinizi burada paylaşabilirsiniz.'}</p></div></section>
  return <footer style={{background:p.bg,color:p.text}}><div className="mx-auto max-w-5xl border-t px-5 py-12 text-center" style={{borderColor:p.accent+'44'}}><Heart className="mx-auto h-5 w-5" style={{color:p.accent}}/><p className="mt-4 font-serif text-2xl">{names}</p><p className="mt-3 text-xs" style={{color:p.muted}}>{props.message||'Bu güzel günde bizimle olduğunuz için teşekkür ederiz.'}</p></div></footer>
}
function Info({icon:Icon,label,value,p}){return <div className="p-6 text-center" style={{background:p.bg}}><Icon className="mx-auto h-5 w-5" style={{color:p.accent}}/><p className="mt-3 text-[9px] uppercase tracking-widest" style={{color:p.muted}}>{label}</p><p className="mt-2 font-serif text-lg">{value}</p></div>}
